- name: check php is installed.
  become: no
  shell: php -v
  register: php_is_installed
  changed_when: no
  ignore_errors: yes

- name: install dependencies packages
  yum: name={{ item }}
  with_items: 
    - epel-release
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
  tags: php
  when: php_is_installed|failed

- name: install
  yum: name={{ item }} enablerepo=remi,remi-php70
  with_items: 
    - php
    - php-devel
    - php-mbstring
    - php-pdo
    - php-gd
  tags: php
  when: php_is_installed|failed
