- name: check git is installed.
  become: no
  shell: git --help
  register: git_is_installed
  changed_when: no
  ignore_errors: yes

- name: install dependencies packages
  yum: name={{ item }}
  with_items: 
    - make
    - curl-devel
    - gcc
    - openssl-devel
    - expat-devel
    - cpan
    - gettext
    - asciidoc
    - xmlto
  tags: git
  when: git_is_installed|failed

- name: download source
  get_url: url={{ git_url }}
           dest={{ install_path }}/{{ git_tar }}
  tags: git
  when: git_is_installed|failed

- name: compile & install
  shell: cd {{ install_path }} \
         && tar -zxf {{ git_tar }} \ 
         && cd {{ git_dir_name }} \
         && make prefix=/usr/local all doc \
         && sudo make prefix=/usr/local install install-doc install-html
  tags: git
  when: git_is_installed|failed
